# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Assignment2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Assignment2
	pod 'Cosmos', '~> 23.0'
end
